<?php

namespace Proxies\__CG__\OC\EPIBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheDeVie extends \OC\EPIBundle\Entity\FicheDeVie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'id', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'modele', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'fabriquant', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'identifiantFab', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dateAchat', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dateFabrication', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dateMiseEnService', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dureeDeVie', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'frequenceControle', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'equipements');
        }

        return array('__isInitialized__', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'id', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'modele', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'fabriquant', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'identifiantFab', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dateAchat', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dateFabrication', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dateMiseEnService', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'dureeDeVie', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'frequenceControle', '' . "\0" . 'OC\\EPIBundle\\Entity\\FicheDeVie' . "\0" . 'equipements');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheDeVie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModele($modele)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModele', array($modele));

        return parent::setModele($modele);
    }

    /**
     * {@inheritDoc}
     */
    public function getModele()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModele', array());

        return parent::getModele();
    }

    /**
     * {@inheritDoc}
     */
    public function setFabriquant($fabriquant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFabriquant', array($fabriquant));

        return parent::setFabriquant($fabriquant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFabriquant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFabriquant', array());

        return parent::getFabriquant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentifiantFab($identifiantFab)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentifiantFab', array($identifiantFab));

        return parent::setIdentifiantFab($identifiantFab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifiantFab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifiantFab', array());

        return parent::getIdentifiantFab();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAchat($dateAchat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAchat', array($dateAchat));

        return parent::setDateAchat($dateAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAchat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAchat', array());

        return parent::getDateAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFabrication($dateFabrication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFabrication', array($dateFabrication));

        return parent::setDateFabrication($dateFabrication);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFabrication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFabrication', array());

        return parent::getDateFabrication();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateMiseEnService($dateMiseEnService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateMiseEnService', array($dateMiseEnService));

        return parent::setDateMiseEnService($dateMiseEnService);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateMiseEnService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateMiseEnService', array());

        return parent::getDateMiseEnService();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeDeVie($dureeDeVie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeDeVie', array($dureeDeVie));

        return parent::setDureeDeVie($dureeDeVie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeDeVie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeDeVie', array());

        return parent::getDureeDeVie();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrequenceControle($frequenceControle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrequenceControle', array($frequenceControle));

        return parent::setFrequenceControle($frequenceControle);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrequenceControle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrequenceControle', array());

        return parent::getFrequenceControle();
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipements', array());

        return parent::getEquipements();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipements($equipements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipements', array($equipements));

        return parent::setEquipements($equipements);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', array());

        return parent::getLabel();
    }

}
