<?php

namespace Proxies\__CG__\OC\EPIBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipement extends \OC\EPIBundle\Entity\Equipement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'id', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'numInterne', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'numSerie', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'ficheDeVie', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'controles');
        }

        return array('__isInitialized__', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'id', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'numInterne', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'numSerie', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'ficheDeVie', '' . "\0" . 'OC\\EPIBundle\\Entity\\Equipement' . "\0" . 'controles');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Equipement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumInterne($numInterne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumInterne', array($numInterne));

        return parent::setNumInterne($numInterne);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumInterne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumInterne', array());

        return parent::getNumInterne();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSerie($numSerie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSerie', array($numSerie));

        return parent::setNumSerie($numSerie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSerie', array());

        return parent::getNumSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function getFicheDeVie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFicheDeVie', array());

        return parent::getFicheDeVie();
    }

    /**
     * {@inheritDoc}
     */
    public function setFicheDeVie($ficheDeVie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFicheDeVie', array($ficheDeVie));

        return parent::setFicheDeVie($ficheDeVie);
    }

    /**
     * {@inheritDoc}
     */
    public function getControles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControles', array());

        return parent::getControles();
    }

    /**
     * {@inheritDoc}
     */
    public function setControles($controles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setControles', array($controles));

        return parent::setControles($controles);
    }

}
